"""Add order field to Task model

Revision ID: a5e7ad83a91d
Revises: ebeab912352f
Create Date: 2026-01-09 09:37:22.929429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e7ad83a91d'
down_revision: Union[str, Sequence[str], None] = 'ebeab912352f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# So, sqlite doesn't really play well with altering columns.  For now, what I'm going to do is use the batch_alter_table to copy existing data to a new table.  I will want to revise this as we move toward postgresql.

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), default=0))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('order')
    # ### end Alembic commands ###
